# Generated by Django 3.2.8 on 2021-12-02 15:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_name', models.CharField(max_length=50)),
                ('image_caption', models.TextField(max_length=100)),
                ('image_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
